#!/usr/bin/env bash
set -euo pipefail

# Generates nginx host→city map from cities.txt (first letter shortcuts).
# Usage: generate-short-urls.sh

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CITIES_FILE="$ROOT/cities.txt"
OUT="$ROOT/short-urls/nginx.conf"

mkdir -p "$(dirname "$OUT")"

{
  echo "# Generated by generate-short-urls.sh — do not edit by hand"
  echo "map \$host \$preview_redirect_base {"
  echo '    default "";'

  while read -r city; do
    [[ -n "$city" ]] || continue
    letter=${city:0:1}
    echo "    ${letter}.codies.se https://${city}.codies.se;"
  done < "$CITIES_FILE"

  cat <<'NGINX'
}

server {
    listen 8080;

    location / {
        if ($preview_redirect_base = "") {
            return 404;
        }
        return 301 $preview_redirect_base$request_uri;
    }
}
NGINX
} > "$OUT"

echo "Wrote $OUT"
