#!/usr/bin/env bash
set -euo pipefail

# Generates Traefik redirect routers from cities.txt (first-letter shortcuts).
# Usage: generate-traefik-shortcuts.sh

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CITIES_FILE="$ROOT/cities.txt"
OUT="$ROOT/../traefik/dynamic/preview-shortcuts.yaml"

mkdir -p "$(dirname "$OUT")"

{
  echo "# Generated by generate-traefik-shortcuts.sh — edit cities.txt and re-run"
  echo "http:"
  echo "  middlewares:"

  while read -r city; do
    [[ -n "$city" ]] || continue
    letter=${city:0:1}
    echo "    preview-short-${letter}: {redirectRegex: {permanent: true, regex: \"^https?://${letter}\\\\.codies\\\\.se.*\", replacement: \"https://${city}.codies.se/\"}}"
  done < "$CITIES_FILE"

  echo "  routers:"

  while read -r city; do
    [[ -n "$city" ]] || continue
    letter=${city:0:1}
    echo "    preview-short-${letter}: {rule: Host(\`${letter}.codies.se\`), entryPoints: [websecure], middlewares: [preview-short-${letter}], service: ping@internal, tls: {certResolver: letsencrypt}}"
  done < "$CITIES_FILE"
} > "$OUT"

echo "Wrote $OUT"
