- id: ccf2b80b3c4e4080b7e7ea0969afc666
  alias: Alarm Clock - Wake me up with lights
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == ((states.input_datetime.wakeup_time.attributes.timestamp
      | int) - (states.input_datetime.light_transition_time.attributes.timestamp |
      int)) | timestamp_custom("%H:%M", False) }}'
  condition:
  - condition: state
    entity_id: input_boolean.wakeup_enabled
    state: 'on'
  - condition: or
    conditions:
    - condition: state
      entity_id: input_boolean.wakeup_weekend
      state: 'on'
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  - condition: state
    entity_id: sensor.someone_home
    state: 'True'
  action:
  - data_template:
      brightness: 255
      entity_id:
      - group.bedroom
      rgb_color:
      - 255
      - 180
      - 100
      transition: '{{ states.input_datetime.light_transition_time.attributes.timestamp
        | int }}'
    service: light.turn_on
  - service: script.turn_on
    data: {}
    entity_id: script.pulsing_lights
  - delay: '{{ states.input_datetime.light_transition_time.attributes.timestamp |
      int }}'
  - data:
      entity_id:
      - switch.hallway_plug
      - switch.sonoff_10008c59d6
    service: switch.turn_on
  - data:
      brightness: 200
      entity_id:
      - light.hallway_door
      - light.kitchen_table
      - light.kitchen_oven
      - light.kitchen_sink
    service: light.turn_on
  - service: cover.open_cover
    data:
      entity_id:
      - cover.bedroom_blind_l
      - cover.bedroom_blind_r
  - service: script.play_spotify
    data:
      entity_id: media_player.speakers
      uri: input_text.good_morning_playlist
  mode: single
- id: '1575459544999'
  alias: Arrive Home - Turn on lights
  description: ''
  trigger:
  - entity_id: sensor.someone_home
    from: 'False'
    platform: state
    to: 'True'
  condition: []
  action:
  - data: {}
    service: script.power_on
  mode: single
- id: '1575958785836'
  alias: Goodnight - Turn off the lights
  description: ''
  trigger: []
  condition: []
  action:
  - service: cover.close_cover
    data:
      entity_id:
      - cover.bedroom_blind_l
      - cover.bedroom_blind_r
  - data:
      brightness: 10
      entity_id:
      - light.philips_hue
      transition: 10
    service: light.turn_on
  - delay: 00:00:12
  - data: {}
    service: script.power_off
  - entity_id: light.philips_hue
    service: light.turn_on
    data:
      brightness: 50
      rgb_color:
      - 255
      - 150
      - 40
  - data_template:
      entity_id:
      - light.philips_hue
      transition: '{{ states.input_datetime.goodnight_transition_time.attributes.timestamp
        | int }}'
      brightness: 0
      rgb_color:
      - 255
      - 0
      - 0
    service: light.turn_on
  mode: single
- id: '1576047741633'
  alias: Leave Home - Turn off lights
  description: ''
  trigger:
  - entity_id: sensor.someone_home
    for: 00:05
    from: 'True'
    platform: state
    to: 'False'
  condition: []
  action:
  - data: {}
    service: script.power_off
- id: '1578430362392'
  alias: 'Arrive Home - Victor '
  description: ''
  trigger:
  - entity_id: person.victor
    event: enter
    platform: zone
    zone: zone.home
  condition:
  - after: '10:00:00'
    before: '19:00:00'
    condition: time
  - condition: device
    device_id: 334e513fb3de4085bbf4e1807f574000
    domain: media_player
    entity_id: media_player.sorrysound_audio
    type: is_off
  action:
  - data:
      volume_level: 0.4
    entity_id: media_player.portable_speaker
    service: media_player.volume_set
  - data:
      entity_id: media_player.speakers
      uri: input_text.arrive_home_playlist
    service: script.play_spotify
  mode: single
- id: '1581713291992'
  alias: Evening - Dim lights
  description: ''
  trigger:
  - at: '20:30'
    platform: time
  condition:
  - condition: state
    entity_id: group.ikea
    state: 'on'
  - condition: state
    entity_id: sensor.someone_home
    state: 'True'
  action:
  - condition: or
    conditions:
    - condition: time
      after: '20:15'
      before: '8:00'
    - condition: sun
      after: sunset
      after_offset: -00:30:00
  - data:
      entity_id:
      - light.hallway_kitchen
      - light.kitchen_oven
      - light.kitchen_sink
    service: light.turn_off
  - data:
      brightness: 20
      entity_id:
      - light.kitchen_table
      - light.hallway_door
      - light.hallway_spots
    service: light.turn_on
  - data: {}
    entity_id: switch.outdoor_plug
    service: switch.turn_on
  mode: single
- id: power_off_for_work
  alias: Power off - @Work
  description: ''
  trigger:
  - at: 09:00
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: script.power_off
  - data: {}
    entity_id: switch.sonoff_10008c59d6
    service: switch.turn_on
- id: '1587480240661'
  alias: Brigthness Slider
  description: ''
  trigger:
  - entity_id: input_number.light_brightness
    platform: state
  condition:
  - condition: state
    entity_id: sensor.someone_home
    state: 'True'
  action:
  - data_template:
      brightness: '{{ ((trigger.to_state.state | float) * 2.54) | int }}'
      entity_id: '{{ states.light | selectattr(''state'',''eq'',''on'') | map(attribute=''entity_id'')
        | join('','') }}

        '
    service: light.turn_on
- id: '1589916252189'
  alias: Remote Control - Listener
  description: ''
  trigger:
  - event_data: {}
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data_template:
      entity_id: input_select.remote_entity
      id: '{{ trigger.event.as_dict()["data"].id }}'
      event: '{{ trigger.event.as_dict()["data"].event }}'
    service: vicnie.remote_control
  mode: single
- id: '1606157917188'
  alias: Sunset - Balcony Lights
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:30:00
  condition:
  - condition: state
    entity_id: sensor.someone_home
    state: 'True'
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.outdoor_plug
  mode: single
