- id: ccf2b80b3c4e4080b7e7ea0969afc666
  alias: Alarm Clock - Weekday
  description: ''
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == ((states.input_datetime.wakeup_weekday_time.attributes.timestamp
      | int) - (states(''input_number.wakeup_transition_time'') | int * 60)) | timestamp_custom("%H:%M",
      False) }}'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.wakeup_weekday
      state: 'on'
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  - condition: state
    entity_id: sensor.someone_home
    state: 'True'
  action:
  - service: light.turn_on
    data:
      brightness_pct: 1
      rgb_color:
      - 166
      - 44
      - 23
    target:
      entity_id:
      - light.bedroom
      - light.philips_hue
  - service: light.turn_on
    data:
      transition: '{{ states(''input_number.wakeup_transition_time'') | int * 60 }}'
      brightness_pct: 100
      rgb_color:
      - 255
      - 255
      - 255
    target:
      entity_id:
      - light.bedroom
      - light.philips_hue
  - delay: '{{ states(''input_number.wakeup_transition_time'') | int * 60 }}'
  - service: script.turn_on
    entity_id: script.good_morning
  mode: restart
- id: '1575459544999'
  alias: Arrive Home - Turn on lights
  description: ''
  trigger:
  - entity_id: sensor.someone_home
    from: 'False'
    platform: state
    to: 'True'
  condition: []
  action:
  - data: {}
    service: script.power_on
  mode: single
- id: '1576047741633'
  alias: Leave Home - Turn off lights
  description: ''
  trigger:
  - entity_id: sensor.someone_home
    for: 00:05
    from: 'True'
    platform: state
    to: 'False'
  condition: []
  action:
  - data: {}
    service: script.power_off
- id: '1578430362392'
  alias: 'Arrive Home - Victor '
  description: ''
  trigger:
  - entity_id: person.victor
    event: enter
    platform: zone
    zone: zone.home
  condition:
  - after: '10:00:00'
    before: '19:00:00'
    condition: time
  - condition: state
    entity_id: media_player.rio
    state: 'off'
  action:
  - wait_template: '{{ is_state(''media_player.spotify_thessound'', ''idle'') }}'
    continue_on_timeout: false
    timeout: 00:15:00
  - data:
      volume_level: 0.4
    service: media_player.volume_set
    target:
      entity_id:
      - media_player.kasinot_speaker
  - data:
      entity_id: media_player.speakers
      uri: input_text.arrive_home_playlist
      account: mr
    service: script.play_spotify
  mode: single
- id: '1581713291992'
  alias: Evening - Dim lights
  description: ''
  trigger:
  - at: '20:30:00'
    platform: time
  condition:
  - condition: state
    entity_id: group.ikea
    state: 'on'
  - condition: state
    entity_id: sensor.someone_home
    state: 'True'
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - sun
  - condition: state
    entity_id: group.dining
    state: 'off'
  action:
  - condition: time
    after: '20:15:00'
    before: 05:00:00
  - service: script.dim_lights
    data: {}
  mode: single
- id: power_off_for_work
  alias: Power off - @Work
  description: ''
  trigger:
  - at: 09:00
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: state
    entity_id: sensor.someone_home
    state: 'True'
  action:
  - service: script.power_off
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - data: {}
    entity_id: switch.sonoff_10008c59d6
    service: switch.turn_on
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: switch.turn_on
    target:
      entity_id: switch.sonoff_10008c59d6
  mode: single
- id: '1587480240661'
  alias: Brigthness Slider
  description: ''
  trigger:
  - entity_id: input_number.light_brightness
    platform: state
  condition:
  - condition: state
    entity_id: sensor.someone_home
    state: 'True'
  action:
  - data_template:
      brightness: '{{ ((trigger.to_state.state | float) * 2.54) | int }}'
      entity_id: '{{ states.light | selectattr(''state'',''eq'',''on'') | map(attribute=''entity_id'')
        | join('','') }}

        '
    service: light.turn_on
- id: '1589916252189'
  alias: Remote Control - Listener
  description: ''
  trigger:
  - event_data: {}
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data_template:
      id: '{{ trigger.event.data.id }}'
      event: '{{ trigger.event.data.event }}'
      gesture: '{{ trigger.event.data.gesture }}'
    service: vicnie.remote_control
  mode: single
- id: '1606157917188'
  alias: Sunset - Balcony Lights
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:30:00
  condition:
  - condition: state
    entity_id: sensor.someone_home
    state: 'True'
  action:
  - condition: sun
    after: sunset
    before: sunrise
    after_offset: -00:00:30
  - service: switch.turn_on
    data: {}
    target:
      entity_id:
      - switch.power_strip_socket_1
  mode: single
- id: '1607431749233'
  alias: Bodypump
  description: ''
  trigger:
  - platform: time
    at: 05:45:00
  condition:
  - condition: time
    weekday:
    - wed
    before: 00:00:00
    after: 00:00:00
  - condition: state
    entity_id: sensor.someone_home
    state: 'True'
  action:
  - parallel:
    - service: script.blinds_open
      data: {}
    - service: script.power_on
      data: {}
    - service: light.turn_on
      data:
        rgb_color:
        - 118
        - 187
        - 64
      target:
        entity_id:
        - light.bedroom
        - light.kitchen_table
        - light.philips_hue
    - service: spotcast.start
      data:
        entity_id: media_player.speakers
        random_song: true
        repeat: context
        shuffle: true
        uri: spotify:playlist:37i9dQZF1DX7CB1M7sBt21
        account: mr
  mode: restart
- id: '1608451314385'
  alias: Bedroom brightness
  description: ''
  trigger:
  - platform: event
    event_type: state_changed
    event_data:
      entity_id: light.bedroom
  condition:
  - condition: template
    value_template: '{{ trigger.event.data.old_state.state == "off" }}'
  - condition: template
    value_template: '{{ trigger.event.data.new_state.state == "on" }}'
  - condition: template
    value_template: '{{ trigger.event.data.new_state.context.user_id is none }}'
  - condition: template
    value_template: '{{ trigger.event.data.new_state.context.parent_id is none }}'
  action:
  - service: light.turn_on
    data:
      brightness: 255
    entity_id: light.bedroom
  mode: single
- id: '1624548713213'
  alias: Prepare Good Night
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.time_until_alarm
    below: '9.0'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - sun
    before: 00:00:00
    after: 00:00:00
  - condition: state
    entity_id: sensor.someone_home
    state: 'True'
  - condition: state
    entity_id: input_boolean.wakeup_weekday
    state: 'on'
  - condition: state
    entity_id: group.ikea
    state: 'on'
  action:
  - service: light.turn_on
    data_template:
      entity_id: '{{ states.light | selectattr(''state'',''eq'',''on'') | map(attribute=''entity_id'')
        | join('','') }}'
      flash: short
  - service: input_number.set_value
    target:
      entity_id: input_number.light_brightness
    data:
      value: 10
  - condition: not
    conditions:
    - condition: state
      entity_id: media_player.rio
      state: playing
    - condition: state
      entity_id: media_player.kasinot_speaker
      state: playing
  - condition: state
    entity_id: media_player.mio_tv
    state: 'off'
  - service: script.play_spotify
    data:
      uri: input_text.goodnight_playlist
      account: mr
      entity_id: media_player.speakers
  mode: single
- id: '1660077043222'
  alias: Watering Plants
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 0
  condition:
  - condition: time
    weekday:
    - fri
  action:
  - wait_template: '{{ states(''switch.water_pump_switch'') == ''off'' }}'
    continue_on_timeout: false
    timeout: 01:00:00
  - service: notify.mobile_app_victors_ipod_2
    data:
      title: Watering Plants
      message: '{{ ''Initial watering at '' + as_timestamp(now()) | timestamp_custom(''%H:%M'')  }}'
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.water_pump_switch
  - wait_template: '{{ states(''switch.water_pump_switch'') == ''off'' }}'
    continue_on_timeout: false
    timeout: 01:00:00
  - delay:
      hours: 0
      minutes: 30
      seconds: 0
      milliseconds: 0
  - wait_template: '{{ states(''switch.water_pump_switch'') == ''off'' }}'
    continue_on_timeout: false
    timeout: 01:00:00
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.water_pump_switch
  - service: notify.mobile_app_victors_ipod_2
    data:
      title: Watering Plants
      message: '{{ ''Done watering at '' + as_timestamp(now()) | timestamp_custom(''%H:%M'')  }}'
  mode: single
- id: '1666530802374'
  alias: TV Lights - Listener
  description: ''
  trigger:
  - platform: state
    entity_id:
    - media_player.mio_tv
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: light.living_room
    state: 'off'
  action:
  - service: light.turn_on
    data:
      transition: 10
      brightness_pct: 60
    target:
      entity_id:
      - light.led_strip_philips
      - light.led_strip_lifx
  - service: light.turn_on
    data:
      transition: 10
      brightness_pct: 10
    target:
      entity_id: light.living_room
  mode: single
- id: '1666531317595'
  alias: Lunch time - Turn on lights
  description: ''
  trigger:
  - platform: time
    at: '12:00:00'
  condition:
  - condition: state
    entity_id: sensor.someone_home
    state: 'True'
  action:
  - service: script.power_on
    data: {}
  - service: light.turn_on
    data:
      brightness_pct: 100
    target:
      entity_id:
      - light.kitchen_oven
      - light.kitchen_sink
      - light.kitchen_table
  mode: single
- id: '1672304388800'
  alias: Vacation - Balcony On
  description: ''
  trigger:
  - platform: time
    at: 07:00:00
  - platform: time
    at: '16:00:00'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id:
      - switch.power_strip_socket_3
      - switch.power_strip_socket_1
  mode: single
- id: '1672304661695'
  alias: Vacation - Balcony Off
  description: ''
  trigger:
  - platform: time
    at: 09:00:00
  - platform: time
    at: '21:00:00'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id:
      - switch.power_strip_socket_1
      - switch.power_strip_socket_3
  mode: single
- id: '1683892739577'
  alias: Plant needs water - Notify
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 0
  condition:
  - condition: numeric_state
    entity_id: sensor.plant_sensor_282f_conductivity
    below: 350
  action:
  - service: notify.mobile_app_victors_ipod_2
    data:
      title: Plants needs water!
      message: '{{ ''Plants: '' + states(''sensor.plant_sensor_282f_conductivity'')
        + ''µS/cm, '' + states(''sensor.plant_sensor_282f_moisture'') + ''%'' }}'
  mode: single
- id: '1688329161680'
  alias: Water Pump Duration - Changed
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.water_pump_duration
    for:
      hours: 0
      minutes: 10
      seconds: 0
    attribute: raw_state
    below: 100
  condition: []
  action:
  - service: notify.mobile_app_victors_ipod_2
    data:
      title: Water Pump Duration - CHANGED!
      message: '{{ ''New duration: '' + states(''sensor.water_pump_duration'') + ''s
        (< 100)'' }}'
  mode: single
- id: '1701035317867'
  alias: Clara is cleaning
  description: ''
  trigger:
  - platform: time
    at: 08:00:00
  condition:
  - condition: time
    weekday:
    - mon
    - thu
  action:
  - service: notify.mobile_app_victors_ipod_2
    data:
      title: Cleanmate
      message: Clara vill ha bort mattan
      data:
        tag: cleaning
  - delay:
      hours: 2
      minutes: 0
      seconds: 0
      milliseconds: 0
  - service: notify.mobile_app_victors_ipod_2
    data:
      message: clear_notification
      data:
        tag: cleaning
  mode: single
- id: '1701042405778'
  alias: Chef - Victor
  description: ''
  trigger:
  - platform: time
    at: '16:00:00'
  condition:
  - condition: or
    conditions:
    - condition: and
      conditions:
      - condition: time
        weekday:
        - mon
      - condition: state
        entity_id: input_select.chef_monday
        state: chef-man
    - condition: and
      conditions:
      - condition: time
        weekday:
        - tue
      - condition: state
        entity_id: input_select.chef_tuesday
        state: chef-man
    - condition: and
      conditions:
      - condition: time
        weekday:
        - wed
      - condition: state
        entity_id: input_select.chef_wednesday
        state: chef-man
    - condition: and
      conditions:
      - condition: time
        weekday:
        - thu
      - condition: state
        entity_id: input_select.chef_thursday
        state: chef-man
  action:
  - service: notify.mobile_app_victors_ipod_2
    data:
      title: Middag
      message: Laga mat ikväll
  mode: single
- id: '1701520528599'
  alias: Alarm Clock - Weekend
  description: ''
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == ((states.input_datetime.wakeup_weekend_time.attributes.timestamp
      | int) - (states(''input_number.wakeup_transition_time'') | int * 60)) | timestamp_custom("%H:%M",
      False) }}'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.wakeup_weekend
      state: 'on'
    - condition: time
      weekday:
      - sat
      - sun
  - condition: state
    entity_id: sensor.someone_home
    state: 'True'
  action:
  - service: light.turn_on
    data:
      brightness_pct: 1
      rgb_color:
      - 166
      - 44
      - 23
    target:
      entity_id:
      - light.bedroom
      - light.philips_hue
  - service: light.turn_on
    data:
      transition: '{{ states(''input_number.wakeup_transition_time'') | int * 60 }}'
      brightness_pct: 100
      rgb_color:
      - 255
      - 255
      - 255
    target:
      entity_id:
      - light.bedroom
      - light.philips_hue
  - delay: '{{ states(''input_number.wakeup_transition_time'') | int * 60 }}'
  - service: script.turn_on
    entity_id: script.good_morning
  mode: restart
- id: '1701712494987'
  alias: Leaves Job - Mr
  description: ''
  trigger:
  - platform: zone
    entity_id: person.victor
    zone: zone.tedsys
    event: leave
  - platform: zone
    entity_id: person.victor
    zone: zone.yale
    event: leave
  condition:
  - condition: time
    after: '14:00:00'
    before: '20:00:00'
  - condition: state
    entity_id: person.annie
    state: home
  action:
  - service: notify.mobile_app_ms
    data:
      message: "Nu går jag från jobbet xoxo \U0001F618❤️"
      title: Victor
  mode: single
- id: '1701712730012'
  alias: Leaves Job - Ms
  description: ''
  trigger:
  - platform: zone
    entity_id: person.annie
    zone: zone.tactel
    event: leave
  condition:
  - condition: time
    after: '14:00:00'
    before: '20:00:00'
  - condition: state
    entity_id: person.victor
    state: home
  action:
  - service: notify.mobile_app_victors_ipod_2
    data:
      message: "Nu går jag från jobbet xoxo \U0001F618❤️"
      title: Annie
  mode: single
- id: '1704141083682'
  alias: Good Night - Trigger
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.mr_battery_state
    from: Not Charging
    to: Charging
  - platform: state
    entity_id:
    - sensor.ms_battery_state
    from: discharging
    to: charging
  condition:
  - condition: state
    entity_id: sensor.someone_home
    state: 'True'
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - sun
    after: '20:30:00'
    before: '23:00:00'
  - condition: state
    entity_id: media_player.mio_tv
    state: 'off'
  - condition: state
    entity_id: group.dining
    state: 'off'
  action:
  - service: notify.notify
    data:
      title: Good Night Mode Activated (5 min)
      data:
        tag: goodnight
      message: "Home Assistant says goodnight! Sweet dreams. \U0001F319\U0001F4A4"
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: notify.notify
    data:
      message: clear_notification
      data:
        tag: goodnight
  - service: script.good_night
    data: {}
  mode: single
- id: '1705497213363'
  alias: Printing - Notify
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.ender_3_print_status
  condition: []
  action:
  - service: notify.mobile_app_victors_ipod_2
    data:
      title: Ender 3D Printer
      message: '{{states(''sensor.ender_3_print_status'') }}'
  mode: single
