- id: ccf2b80b3c4e4080b7e7ea0969afc666
  alias: Alarm Clock - Wake me up with lights
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == ((states.input_datetime.wakeup_time.attributes.timestamp
      | int) - (states.input_datetime.light_transition_time.attributes.timestamp |
      int)) | timestamp_custom("%H:%M", False) }}'
  condition:
  - condition: state
    entity_id: input_boolean.wakeup_enabled
    state: 'on'
  - condition: or
    conditions:
    - condition: state
      entity_id: input_boolean.wakeup_weekend
      state: 'on'
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  - condition: state
    entity_id: sensor.someone_home
    state: 'True'
  action:
  - service: script.turn_on
    data: {}
    entity_id: script.pulsing_lights
  - delay: '{{ states.input_datetime.light_transition_time.attributes.timestamp |
      int }}'
  - service: script.turn_on
    entity_id: script.good_morning
  mode: single
- id: '1575459544999'
  alias: Arrive Home - Turn on lights
  description: ''
  trigger:
  - entity_id: sensor.someone_home
    from: 'False'
    platform: state
    to: 'True'
  condition: []
  action:
  - data: {}
    service: script.power_on
  mode: single
- id: '1576047741633'
  alias: Leave Home - Turn off lights
  description: ''
  trigger:
  - entity_id: sensor.someone_home
    for: 00:05
    from: 'True'
    platform: state
    to: 'False'
  condition: []
  action:
  - data: {}
    service: script.power_off
- id: '1578430362392'
  alias: 'Arrive Home - Victor '
  description: ''
  trigger:
  - entity_id: person.victor
    event: enter
    platform: zone
    zone: zone.home
  condition:
  - after: '10:00:00'
    before: '19:00:00'
    condition: time
  - condition: device
    device_id: 334e513fb3de4085bbf4e1807f574000
    domain: media_player
    entity_id: media_player.sorrysound_audio
    type: is_off
  action:
  - data:
      volume_level: 0.4
    entity_id: media_player.portable_speaker
    service: media_player.volume_set
  - data:
      entity_id: media_player.speakers
      uri: input_text.arrive_home_playlist
      account: mr
    service: script.play_spotify
  mode: single
- id: '1581713291992'
  alias: Evening - Dim lights
  description: ''
  trigger:
  - at: '20:30'
    platform: time
  condition:
  - condition: state
    entity_id: group.ikea
    state: 'on'
  - condition: state
    entity_id: sensor.someone_home
    state: 'True'
  action:
  - condition: time
    after: '20:15'
    before: 05:00
  - service: script.dim_lights
  mode: single
- id: power_off_for_work
  alias: Power off - @Work
  description: ''
  trigger:
  - at: 09:00
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: state
    entity_id: sensor.someone_home
    state: 'True'
  action:
  - service: script.power_off
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - data: {}
    entity_id: switch.sonoff_10008c59d6
    service: switch.turn_on
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: switch.turn_on
    target:
      entity_id: switch.sonoff_10008c59d6
  mode: single
- id: '1587480240661'
  alias: Brigthness Slider
  description: ''
  trigger:
  - entity_id: input_number.light_brightness
    platform: state
  condition:
  - condition: state
    entity_id: sensor.someone_home
    state: 'True'
  action:
  - data_template:
      brightness: '{{ ((trigger.to_state.state | float) * 2.54) | int }}'
      entity_id: '{{ states.light | selectattr(''state'',''eq'',''on'') | map(attribute=''entity_id'')
        | join('','') }}

        '
    service: light.turn_on
- id: '1589916252189'
  alias: Remote Control - Listener
  description: ''
  trigger:
  - event_data: {}
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data_template:
      id: '{{ trigger.event.data.id }}'
      event: '{{ trigger.event.data.event }}'
      gesture: '{{ trigger.event.data.gesture }}'
    service: vicnie.remote_control
  mode: single
- id: '1606157917188'
  alias: Sunset - Balcony Lights
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:30:00
  condition:
  - condition: state
    entity_id: sensor.someone_home
    state: 'True'
  action:
  - condition: sun
    after: sunset
    before: sunrise
    after_offset: -00:00:30
  - service: switch.turn_on
    data: {}
    target:
      entity_id:
      - switch.window_plug
      - switch.power_strip_3
      - switch.power_strip_2
  mode: single
- id: '1607431749233'
  alias: Bodypump
  description: ''
  trigger:
  - platform: time
    at: 05:30
  condition:
  - condition: time
    weekday:
    - wed
  - condition: state
    entity_id: sensor.someone_home
    state: 'True'
  action:
  - service: script.turn_on
    data: {}
    entity_id: script.pulsing_lights
  - delay:
      hours: 0
      minutes: 15
      seconds: 0
      milliseconds: 0
  - service: script.good_morning
    data: {}
  - service: spotcast.start
    data:
      entity_id: media_player.speakers
      random_song: true
      repeat: context
      shuffle: true
      uri: spotify:playlist:37i9dQZF1DX7CB1M7sBt21
      account: ms
  mode: single
- id: '1608451314385'
  alias: Bedroom brightness
  description: ''
  trigger:
  - platform: state
    entity_id: light.bedroom
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness: 255
    entity_id: light.bedroom
  mode: single
- id: '1624548713213'
  alias: Prepare Good Night
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.time_until_alarm
    below: '9.0'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - sun
  - condition: state
    entity_id: sensor.someone_home
    state: 'True'
  - condition: state
    entity_id: input_boolean.wakeup_enabled
    state: 'on'
  - condition: state
    entity_id: group.ikea
    state: 'on'
  - condition: not
    conditions:
    - condition: state
      entity_id: media_player.sorrysound_audio
      state: playing
  - condition: state
    entity_id: media_player.mio_tv
    state: 'off'
  action:
  - service: light.turn_on
    data_template:
      entity_id: '{{ states.light | selectattr(''state'',''eq'',''on'') | map(attribute=''entity_id'')
        | join('','') }}'
      flash: short
  - service: input_number.set_value
    target:
      entity_id: input_number.light_brightness
    data:
      value: 10
  - condition: state
    entity_id: media_player.mio_tv
    state: 'on'
  - service: script.play_spotify
    data:
      uri: input_text.goodnight_playlist
      account: mr
      entity_id: media_player.speakers
  mode: single
- id: '1635226651435'
  alias: Certificate Expiration
  description: ''
  use_blueprint:
    path: bkbilly/certificate-expiration.yaml
    input:
      time_input: '15:00:00'
      certificate_input: sensor.cert_expiry_timestamp_zolly_ml
      notify_device: 5275297c6b106d98dd2ff5c406835899
- id: '1644946599907'
  alias: Flashing lights
  description: ''
  use_blueprint:
    path: myGithub-Markus/flashing_lights.yaml
    input:
      target_lights:
        entity_id:
        - light.bedroom
        - light.philips_hue
        - light.kitchen_oven
      activated: input_boolean.flashing_lights
      delay: 300
