# Default
default_config:

# Custom
mobile_app:
bluetooth:
wake_on_lan:
vicnie:
tedsys:
sonoff:
spotcast:
  sp_dc: !secret sp_mr_dc
  sp_key: !secret sp_mr_key
  accounts:
    mr:
      sp_dc: !secret sp_mr_dc
      sp_key: !secret sp_mr_key
    ms:
      sp_dc: !secret sp_ms_dc
      sp_key: !secret sp_ms_key

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
    - 62.63.212.167

tts:
  - platform: google_translate

google_assistant:
  project_id: homeassistant-273413
  service_account: !include gcp_homeassistant_service_account.json
  report_state: true
  entity_config:
    script.blinds_close:
      name: Blinds Close
      expose: true
      aliases:
        - Close Blinds
    script.blinds_open:
      name: Blinds Open
      expose: true
      aliases:
        - Open Blinds
    script.pulsing_lights:
      name: Pulsing Lights
      expose: true
    script.power_on:
      name: Power On
      expose: true
    script.power_off:
      name: Power Off
      expose: true
    script.goodnight_at_night:
      name: Goodnight
      expose: true

homeassistant:
  external_url: "https://home.codies.se"
  customize:
    person.victor:
      entity_picture: "/local/victor.jpg"
    person.annie:
      entity_picture: "/local/annie.jpg"

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
template: !include templates.yaml
frontend:
  themes: !include_dir_merge_named themes

# Variables
input_boolean:
  wakeup_weekday:
    name: "Wake-up on weekdays"
    icon: mdi:alarm
  wakeup_weekend:
    name: "Wake-up on weekends"
    icon: mdi:alarm

input_datetime:
  wakeup_weekday_time:
    name: "Start weekday alarm at"
    has_time: true
    has_date: false
  wakeup_weekend_time:
    name: "Start weekend alarm at"
    has_time: true
    has_date: false

input_number:
  light_brightness:
    name: "Light brightness"
    min: 0
    max: 100
  color_index:
    name: "Color index"
    min: 0
    max: 100
  wakeup_transition_time:
    name: "Wake-up timer"
    min: 0
    max: 60
    unit_of_measurement: min
    icon: mdi:timer
  goodnight_transition_time:
    name: "Goodnight timer"
    min: 0
    max: 60
    unit_of_measurement: min
    icon: mdi:timer

input_text:
  couple_playlist:
    name: Couple Playlist
#   initial: spotify:playlist:37i9dQZF1EJwWzoTjgyTb5
  annie_playlist:
    name: Annie's Playlist
#   initial: spotify:playlist:37i9dQZEVXcJk8sVwtGBNk
  victor_playlist:
    name: Victor's Playlist
#   initial: spotify:playlist:37i9dQZEVXcWTnWnE5HWDY
  dinner_playlist:
    name: Dinner Playlist
#   initial: spotify:playlist:37i9dQZF1DX4xuWVBs4FgJ
  custom_playlist:
    name: Custom Playlist
#   initial: spotify:playlist:1WJbVVZmtlTUcqms2zbMaH
  goodnight_playlist:
    name: Goodnight Playlist
#   initial: spotify:album:2GMizsQeKeilPBjUjrfqhI
  arrive_home_playlist:
    name: Arrive Home Playlist
#   initial: spotify:playlist:37i9dQZF1DX4WYpdgoIcn6
  good_morning_playlist:
    name: Good morning Playlist
#   initial: spotify:playlist:7EMXXzWZ5dLGFZElF5ohEA
  anniversary_image:
    name: Anniversary Image
    max: 255
  anniversary_entity:
    name: Anniversary Entity
  anniversary_playlist:
    name: Anniversary Playlist

input_select:
  remote_entity:
    name: "Remote Control Entity"
    options:
     - default
     - media_player.speakers
     - media_player.kasinot_speaker
     - media_player.rio
     - media_player.mio_cast
     - media_player.mio_tv
     - light:all
     - light:group.ikea
    icon: mdi:remote
  symfonisk_play_entity:
    name: "Symfonisk Play Entity"
    options:
     - default
     - media_player.speakers
     - media_player.kasinot_speaker
     - media_player.rio
     - media_player.mio_cast
     - media_player.mio_tv
     - light:all
     - light:group.ikea
    icon: mdi:play-box-outline
  symfonisk_wheel_entity:
    name: "Symfonisk Wheel Entity"
    options:
     - default
     - media_player.speakers
     - media_player.kasinot_speaker
     - media_player.rio
     - media_player.mio_cast
     - media_player.mio_tv
     - light:all
     - light:group.ikea
    icon: mdi:circle-outline
  chef_monday:
    name: Chef Monday
    options:
     - chef-woman
     - chef-man
    icon: mdi:chef-hat
  chef_tuesday:
    name: Chef Tuesday
    options:
     - chef-woman
     - chef-man
    icon: mdi:chef-hat
  chef_wednesday:
    name: Chef Wednesday
    options:
     - chef-woman
     - chef-man
    icon: mdi:chef-hat
  chef_thursday:
    name: Chef Thursday
    options:
     - chef-woman
     - chef-man
    icon: mdi:chef-hat
