- platform: time_date
  display_options:
    - 'time'
    - 'date'
- platform: template
  sensors:
    temperature:
      friendly_name: "Weather Temperature"
      unit_of_measurement: 'Celcius'
      value_template: "{{ state_attr('weather.kasinot', 'temperature') }}"
    time_until_alarm:
      friendly_name: "Time until alarm"
      value_template: >
        {% set weekday = now().weekday() %}
        {% set weekend = weekday in [5,6] %}
        {% set t = states.sensor.time.state.split(':') %}
        {% set time = t[0] | int * 60 * 60 + t[1] | int * 60 %}
        {% if weekend %}
          {% set alarm = states.input_datetime.wakeup_weekend_time.attributes.timestamp %}
        {% else %}
          {% set alarm = states.input_datetime.wakeup_weekday_time.attributes.timestamp %}
        {% endif %}
        {% if weekday == 4 and time > alarm %}
          {% set alarm = states.input_datetime.wakeup_weekend_time.attributes.timestamp %}
        {% elif weekday == 6 and time > alarm %}
          {% set alarm = states.input_datetime.wakeup_weekday_time.attributes.timestamp %}
        {% endif %}
        {% set until = alarm - time + 60 * 60 * 24 %}
        {{ ((until % (60 * 60 * 24)) / (60 * 60)) | round(1) }}
    someone_home:
      friendly_name: "Someone home?"
      value_template: '{{ is_state("person.annie", "home") or is_state("person.victor", "home") }}'
    ender_3_print_image:
      friendly_name: "Ender 3 Print Image"
      value_template: "{{ 'https://print.zolly.eu.org/plugin/UltimakerFormatPackage/thumbnail/' + states('sensor.ender_3_print_file')[:-5] + 'png' }}"
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_use_percent
    - type: processor_use
    - type: load_1m
    - type: load_5m
    - type: load_15m
- platform: spotcast
  country: SE
- platform: rest
  name: OneList
  json_attributes_path: '$.[0]'
  json_attributes:
    - id
    - category
  value_template: >
    {% set json = value_json | selectattr("uid", "eq", 0) | selectattr("checked", "eq", false) | rejectattr("id", "eq", 62) | map(attribute="name") | sort | join("\n") %}
    {{ json[:255] }}
  scan_interval: 30
  resource: https://shop.codies.se/__/products
  headers:
    Authorization: !secret api_key_onelist
