services:
  qr-hunt:
    image: ghcr.io/victorwinberg/qr-hunt:latest
    container_name: qr-hunt
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./credentials.json:/app/credentials.json:ro
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qrhunt.rule=Host(`qr.codies.se`)"
      - "traefik.http.routers.qrhunt.entrypoints=websecure"
      - "traefik.http.routers.qrhunt.tls.certresolver=letsencrypt"
      - "traefik.http.services.qrhunt.loadbalancer.server.port=3000"
      - "dev.dozzle.url=https://qr.codies.se"

networks:
  proxy:
    external: true
