services:
  preview:
    image: ${IMAGE}
    container_name: preview-onemenu-${CITY}
    restart: unless-stopped
    env_file: /opt/stacks/onemenu/.env
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.${CITY}.rule=Host(`${CITY}.codies.se`)
      - traefik.http.routers.${CITY}.entrypoints=websecure
      - traefik.http.routers.${CITY}.tls.certresolver=letsencrypt
      - traefik.http.services.${CITY}.loadbalancer.server.port=3000
      - "dev.dozzle.url=https://${CITY}.codies.se"

networks:
  proxy:
    external: true
