http:
  middlewares:
    preview-short-a: {redirectRegex: {permanent: true, regex: "^https?://a\\.codies\\.se.*", replacement: "https://athens.codies.se/"}}
    preview-short-b: {redirectRegex: {permanent: true, regex: "^https?://b\\.codies\\.se.*", replacement: "https://barcelona.codies.se/"}}
    preview-short-c: {redirectRegex: {permanent: true, regex: "^https?://c\\.codies\\.se.*", replacement: "https://copenhagen.codies.se/"}}
    preview-short-d: {redirectRegex: {permanent: true, regex: "^https?://d\\.codies\\.se.*", replacement: "https://dublin.codies.se/"}}
    preview-short-e: {redirectRegex: {permanent: true, regex: "^https?://e\\.codies\\.se.*", replacement: "https://eslov.codies.se/"}}
    preview-short-f: {redirectRegex: {permanent: true, regex: "^https?://f\\.codies\\.se.*", replacement: "https://florence.codies.se/"}}
    preview-short-g: {redirectRegex: {permanent: true, regex: "^https?://g\\.codies\\.se.*", replacement: "https://gothenburg.codies.se/"}}
    preview-short-h: {redirectRegex: {permanent: true, regex: "^https?://h\\.codies\\.se.*", replacement: "https://helsingborg.codies.se/"}}
    preview-short-i: {redirectRegex: {permanent: true, regex: "^https?://i\\.codies\\.se.*", replacement: "https://ikea.codies.se/"}}
    preview-short-j: {redirectRegex: {permanent: true, regex: "^https?://j\\.codies\\.se.*", replacement: "https://jonkoping.codies.se/"}}
    preview-short-k: {redirectRegex: {permanent: true, regex: "^https?://k\\.codies\\.se.*", replacement: "https://krakow.codies.se/"}}
    preview-short-l: {redirectRegex: {permanent: true, regex: "^https?://l\\.codies\\.se.*", replacement: "https://london.codies.se/"}}
    preview-short-m: {redirectRegex: {permanent: true, regex: "^https?://m\\.codies\\.se.*", replacement: "https://milan.codies.se/"}}
    preview-short-n: {redirectRegex: {permanent: true, regex: "^https?://n\\.codies\\.se.*", replacement: "https://naples.codies.se/"}}
    preview-short-o: {redirectRegex: {permanent: true, regex: "^https?://o\\.codies\\.se.*", replacement: "https://oia.codies.se/"}}
    preview-short-p: {redirectRegex: {permanent: true, regex: "^https?://p\\.codies\\.se.*", replacement: "https://paris.codies.se/"}}
    preview-short-q: {redirectRegex: {permanent: true, regex: "^https?://q\\.codies\\.se.*", replacement: "https://quito.codies.se/"}}
    preview-short-r: {redirectRegex: {permanent: true, regex: "^https?://r\\.codies\\.se.*", replacement: "https://rome.codies.se/"}}
    preview-short-s: {redirectRegex: {permanent: true, regex: "^https?://s\\.codies\\.se.*", replacement: "https://stockholm.codies.se/"}}
    preview-short-t: {redirectRegex: {permanent: true, regex: "^https?://t\\.codies\\.se.*", replacement: "https://tequila.codies.se/"}}
    preview-short-u: {redirectRegex: {permanent: true, regex: "^https?://u\\.codies\\.se.*", replacement: "https://ullared.codies.se/"}}
    preview-short-v: {redirectRegex: {permanent: true, regex: "^https?://v\\.codies\\.se.*", replacement: "https://vienna.codies.se/"}}
    preview-short-w: {redirectRegex: {permanent: true, regex: "^https?://w\\.codies\\.se.*", replacement: "https://washington.codies.se/"}}
    preview-short-x: {redirectRegex: {permanent: true, regex: "^https?://x\\.codies\\.se.*", replacement: "https://xinyang.codies.se/"}}
    preview-short-y: {redirectRegex: {permanent: true, regex: "^https?://y\\.codies\\.se.*", replacement: "https://ystad.codies.se/"}}
    preview-short-z: {redirectRegex: {permanent: true, regex: "^https?://z\\.codies\\.se.*", replacement: "https://zagreb.codies.se/"}}
  routers:
    preview-short:
      rule: HostRegexp(`^[a-z]\.codies\.se$`)
      entryPoints: [websecure]
      middlewares: [preview-short-a,preview-short-b,preview-short-c,preview-short-d,preview-short-e,preview-short-f,preview-short-g,preview-short-h,preview-short-i,preview-short-j,preview-short-k,preview-short-l,preview-short-m,preview-short-n,preview-short-o,preview-short-p,preview-short-q,preview-short-r,preview-short-s,preview-short-t,preview-short-u,preview-short-v,preview-short-w,preview-short-x,preview-short-y,preview-short-z]
      service: ping@internal
      tls: {certResolver: letsencrypt}
