services:
  preview-short:
    image: nginx:alpine
    container_name: preview-short
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy
    labels:
      - "dev.dozzle.url=https://docker.codies.se"

networks:
  proxy:
    external: true
